// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo49BvcLSFMOzKlOuCDI4bZoLKPfw13Mc',
    appId: '1:381573379357:web:5f95dc4702e9bf19715df4',
    messagingSenderId: '381573379357',
    projectId: 'faithful-servant-759bd',
    authDomain: 'faithful-servant-759bd.firebaseapp.com',
    storageBucket: 'faithful-servant-759bd.appspot.com',
    measurementId: 'G-L3KXBCL3V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfRJ6YeL5CGpzYrfrxXVaIx3G5jeKcJT0',
    appId: '1:381573379357:android:8ad468819b72f84b715df4',
    messagingSenderId: '381573379357',
    projectId: 'faithful-servant-759bd',
    storageBucket: 'faithful-servant-759bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNlA0vGINs6MTUITzJHNwQkYmhpcowlA',
    appId: '1:381573379357:ios:2147094806c29595715df4',
    messagingSenderId: '381573379357',
    projectId: 'faithful-servant-759bd',
    storageBucket: 'faithful-servant-759bd.appspot.com',
    iosBundleId: 'com.example.faithfulServant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsNlA0vGINs6MTUITzJHNwQkYmhpcowlA',
    appId: '1:381573379357:ios:2486f0ddb89c3114715df4',
    messagingSenderId: '381573379357',
    projectId: 'faithful-servant-759bd',
    storageBucket: 'faithful-servant-759bd.appspot.com',
    iosBundleId: 'com.example.faithfulServant.RunnerTests',
  );
}
