class Testdb {
  List<Map> db = [
    {
      "name": "كيرلس",
      "address_Area": "ش عبدالله رفاعي",
      "address_Street_Name": 'ش ابو بكر محمد السيد',
      "address_Home_Num": "5",
      "phoneNum1": '01126198158',
      "phoneNum2": '01200602318',
      "qualifications": "بكالريوس هندسة كهرباء",
      "church_code": "1256",
      "current_service": "اولي ابتدائي",
      "current_role": 'امين اسرة',
      "privilege": 'امين خدمة',
    },
    {
      'name': "ابانوب",
      'address_Area': "ش عبدالله رفاعي",
      'address_Street_Name': 'ش ابو بكر محمد السيد',
      'address_Home_Num': 5,
      'phoneNum1': '01126198158',
      'phoneNum2': '01200602318',
      'qualifications': "بكالريوس هندسة كهرباء",
      'church_code': 1256,
      'current_service': "ثانوي بنات",
      'current_role': 'مشرف عام',
      'privilege': 'مشرف عام',
    },
    {
      'name': "ابرام",
      'address_Area': "ش عبدالله رفاعي",
      'address_Street_Name': 'ش ابو بكر محمد السيد',
      'address_Home_Num': 5,
      'phoneNum1': '01126198158',
      'phoneNum2': '01200602318',
      'qualifications': "بكالريوس هندسة كهرباء",
      'church_code': 1256,
      'current_service': "ثانية ابتدائي",
      'current_role': 'خادم',
      'privilege': 'خادم',
    },
    {
      'name': "بيرو",
      'address_Area': "ش عبدالله رفاعي",
      'address_Street_Name': 'ش ابو بكر محمد السيد',
      'address_Home_Num': 5,
      'phoneNum1': '01126198158',
      'phoneNum2': '01200602318',
      'qualifications': "بكالريوس هندسة كهرباء",
      'church_code': 1256,
      'current_service': "سادسة ابتدائي",
      'current_role': 'خادم',
      'privilege': 'خادم', // 1 : abona, 2 : امين الخدمة
    },
    {
      'name': "مريم",
      'address_Area': "ش عبدالله رفاعي",
      'address_Street_Name': 'ش ابو بكر محمد السيد',
      'address_Home_Num': 5,
      'phoneNum1': '01126198158',
      'phoneNum2': '01200602318',
      'qualifications': "بكالريوس هندسة كهرباء",
      'church_code': 1256,
      'current_service': "مساعد امين عام",
      'current_role': 'مساعد امين عام',
      'privilege': 'مشرف عام', // 1 : abona, 2 : امين الخدمة
    },
    {
      'name': "ابونا استفانوس",
      'address_Area': "ش عبدالله رفاعي",
      'address_Street_Name': 'ش ابو بكر محمد السيد',
      'address_Home_Num': 5,
      'phoneNum1': '01126198158',
      'phoneNum2': '01200602318',
      'qualifications': "بكالريوس هندسة كهرباء",
      'church_code': 1256,
      'current_service': "كاهن",
      'current_role': 'مشرف عام',
      'privilege': 'مشرف عام', // 1 : abona, 2 : امين الخدمة
    },
  ];

  Map me = {
    'name': "مينا",
    'address_Area': "ش عبدالله رفاعي",
    'address_Street_Name': 'ش ابو بكر محمد السيد',
    'address_Home_Num': 5,
    'phoneNum1': '01126198158',
    'phoneNum2': '01200602318',
    'qualifications': "بكالريوس هندسة كهرباء",
    'church_code': 1256,
    'current_service': "كاهن",
    'current_role': 'مشرف عام',
    'privilege': 'مشرف عام',
  };
}
